Feature/user expansion
ICTDTWDa3/Client pull request #27
Opened 2024-05-31 16:59 UTC by NielsGooz

2024-05-31 17:00 UTC, NielsGooz commented
Depends on https://github.com/ICTDTWDa3/Server/pull/35

2024-06-02 14:47 UTC, sisimaile requested changes
Some are questions out of interest, the TODO one is legit.

2024-06-02 14:47 UTC, sisimaile commented on src/Views/Header.js
> +
What does the ... do?

2024-06-02 14:59 UTC, NielsGooz commented on src/Enums/AppUserRole.js
Im using flag enum's (bitwise), this way the enum can contain multiple values. 
https://www.c-sharpcorner.com/article/understanding-bitwise-enums-in-c-sharp/

2024-06-02 15:00 UTC, NielsGooz commented on src/Views/Header.js
> +
I left it in because its a genuine button we need, i just havent created the view for it yet.

2024-06-02 15:01 UTC, NielsGooz commented on src/Views/Header.js
> +
it functions like the List.AddRange function in c#. it adds the values of the input array individually instead of adding the array to the array

2024-06-02 17:09 UTC, sisimaile reviewed
Approved

2024-06-02 17:10 UTC, sisimaile approved these changes

2024-06-02 17:16 UTC, merged